language: ruby

sudo: false

cache:
  - apt
  - bundler

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.0

addons:
  apt:
    packages:
      - graphviz

matrix:
  allow_failures:
    - rvm: ruby-head
